# Generated by Django 6.0.2 on 2026-02-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Owner', 'Owner'), ('Finder', 'Finder')], default='owner', max_length=10),
        ),
    ]
