# Generated by Django 6.0.2 on 2026-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_first_name_user_gender_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(max_length=15, null=True),
        ),
    ]
