# Generated by Django 6.0.2 on 2026-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_reward_amount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
