# Generated by Django 6.0.2 on 2026-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
