# Generated by Django 6.0.2 on 2026-03-20 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_latitude_alter_item_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Matching', 'Matching'), ('Recovered', 'Recovered'), ('Blocked', 'Blocked'), ('UnderReview', 'Under Review')], default='Active', max_length=15),
        ),
    ]
