# Generated by Django 6.0.2 on 2026-04-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_role'),
    ]

    operations = [
    ]
