# Generated by Django 6.0.2 on 2026-03-05 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('reporterID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_confidence', models.FloatField()),
                ('match_status', models.CharField(max_length=20)),
                ('found_itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found', to='found.item')),
                ('lost_itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost', to='found.item')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.item')),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='found.user')),
                ('target_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='found.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.match')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.user')),
            ],
        ),
    ]
